package TEGApp;


/**
* TEGApp/baseIOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:58:59 AM VET
*/

public interface baseIOperations 
{
  void shutdown ();
} // interface baseIOperations
