package TEGApp;


/**
* TEGApp/baseS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 18 de noviembre de 2018 09:33:50 PM VET
*/

public final class baseS implements org.omg.CORBA.portable.IDLEntity
{
  public String hostResponse = null;
  public String portResponse = null;
  public String sessionId = null;

  public baseS ()
  {
  } // ctor

  public baseS (String _hostResponse, String _portResponse, String _sessionId)
  {
    hostResponse = _hostResponse;
    portResponse = _portResponse;
    sessionId = _sessionId;
  } // ctor

} // class baseS
