package TEGApp;


/**
* TEGApp/baseIOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 18 de noviembre de 2018 09:33:50 PM VET
*/

public interface baseIOperations 
{
  boolean test ();
  void shutdown ();
} // interface baseIOperations
