package TEGApp;


/**
* TEGApp/CB.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:58:59 AM VET
*/

public final class CB implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String methodName = null;
  public byte params[] = null;

  public CB ()
  {
  } // ctor

  public CB (String _id, String _methodName, byte[] _params)
  {
    id = _id;
    methodName = _methodName;
    params = _params;
  } // ctor

} // class CB
