package TEGApp;

/**
* TEGApp/CBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 18 de noviembre de 2018 09:33:50 PM VET
*/

public final class CBHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.CB value = null;

  public CBHolder ()
  {
  }

  public CBHolder (TEGApp.CB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.CBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.CBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.CBHelper.type ();
  }

}
