package TEGApp;


/**
* TEGApp/CtoB.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:58:59 AM VET
*/

public interface CtoB extends CtoBOperations, TEGApp.baseI, org.omg.CORBA.portable.IDLEntity 
{
} // interface CtoB
