package TEGApp;

/**
* TEGApp/CtoBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:58:59 AM VET
*/

public final class CtoBHolder implements org.omg.CORBA.portable.Streamable
{
  public TEGApp.CtoB value = null;

  public CtoBHolder ()
  {
  }

  public CtoBHolder (TEGApp.CtoB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TEGApp.CtoBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TEGApp.CtoBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TEGApp.CtoBHelper.type ();
  }

}
