module TEGApp {
    struct byt {
        sequence<octet> obj;
    };
    
    struct XC {
        string id;
        string typeResponse;
        sequence<octet> Response;
    };
    
    struct CB {
        string id;
        string methodName;
        sequence<octet> params;
    };
    
    struct XD {
        string schema;
        string queryId;
        sequence<octet> params;
    };
    
    interface baseI {
        oneway void shutdown();
    };
        
    interface CtoB: baseI {
        XC senData(in CB data);
    };
    
    interface XtoD: baseI {
        byt dataRequest(in XD data);
    };
};