package TEGApp;


/**
* TEGApp/baseS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:34:54 AM VET
*/

public final class baseS implements org.omg.CORBA.portable.IDLEntity
{
  public String hostResponse = null;
  public String portResponse = null;

  public baseS ()
  {
  } // ctor

  public baseS (String _hostResponse, String _portResponse)
  {
    hostResponse = _hostResponse;
    portResponse = _portResponse;
  } // ctor

} // class baseS
