package TEGApp;


/**
* TEGApp/CB.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:34:54 AM VET
*/

public final class CB implements org.omg.CORBA.portable.IDLEntity
{
  public TEGApp.baseS infoR = null;
  public String methodName = null;
  public byte params[] = null;

  public CB ()
  {
  } // ctor

  public CB (TEGApp.baseS _infoR, String _methodName, byte[] _params)
  {
    infoR = _infoR;
    methodName = _methodName;
    params = _params;
  } // ctor

} // class CB
