package TEGApp;


/**
* TEGApp/CtoBPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:34:54 AM VET
*/

public abstract class CtoBPOA extends org.omg.PortableServer.Servant
 implements TEGApp.CtoBOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("senData", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TEGApp/CtoB/senData
       {
         TEGApp.CB data = TEGApp.CBHelper.read (in);
         TEGApp.XC $result = null;
         $result = this.senData (data);
         out = $rh.createReply();
         TEGApp.XCHelper.write (out, $result);
         break;
       }

       case 1:  // TEGApp/baseI/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TEGApp/CtoB:1.0", 
    "IDL:TEGApp/baseI:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CtoB _this() 
  {
    return CtoBHelper.narrow(
    super._this_object());
  }

  public CtoB _this(org.omg.CORBA.ORB orb) 
  {
    return CtoBHelper.narrow(
    super._this_object(orb));
  }


} // class CtoBPOA
