package TEGApp;


/**
* TEGApp/CtoBOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:34:54 AM VET
*/

public interface CtoBOperations  extends TEGApp.baseIOperations
{
  TEGApp.XC senData (TEGApp.CB data);
} // interface CtoBOperations
