package TEGApp;


/**
* TEGApp/XD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 18 de noviembre de 2018 09:36:05 PM VET
*/

public final class XD implements org.omg.CORBA.portable.IDLEntity
{
  public String schema = null;
  public String queryId = null;
  public byte params[] = null;

  public XD ()
  {
  } // ctor

  public XD (String _schema, String _queryId, byte[] _params)
  {
    schema = _schema;
    queryId = _queryId;
    params = _params;
  } // ctor

} // class XD
