package TEGApp;


/**
* TEGApp/XtoD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* lunes 17 de diciembre de 2018 09:34:54 AM VET
*/

public interface XtoD extends XtoDOperations, TEGApp.baseI, org.omg.CORBA.portable.IDLEntity 
{
} // interface XtoD
