package TEGApp;


/**
* TEGApp/XtoDOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TEG.idl
* domingo 18 de noviembre de 2018 09:36:05 PM VET
*/

public interface XtoDOperations  extends TEGApp.baseIOperations
{
  TEGApp.byt dataRequest (TEGApp.XD data);
} // interface XtoDOperations
